# Generated by Django 3.0.2 on 2020-02-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compare',
            old_name='propeerties',
            new_name='properties',
        ),
    ]
