# Generated by Django 3.0.2 on 2020-02-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='user',
        ),
    ]
