# Generated by Django 2.2 on 2020-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_area_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='youtube_video',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
