# Generated by Django 2.2 on 2020-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='youtube_video_2',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Youtube 2nd Video ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='youtube_video',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Youtube Video ID'),
        ),
    ]
